import { spawn } from "node:child_process";
import { tmpdir } from "node:os";
import { join, extname } from "node:path";
import { writeFileSync, mkdirSync, readdirSync, rmSync, existsSync, statSync } from "node:fs";
import { loadSettings } from "./config.ts";

const GAMDL_BIN = join(process.env.HOME || "", ".local/bin/gamdl");

export function checkGamdl(): { found: boolean; path: string } {
  const found = existsSync(GAMDL_BIN);
  return { found, path: GAMDL_BIN };
}

function cookiesToNetscape(cookieString: string): string {
  // Build the output as a single string instead of allocating an array + join.
  let out =
    "# Netscape HTTP Cookie File\n" +
    "# This file was generated by catunes\n" +
    "\n";
  const cookies = cookieString.split(";");
  for (let i = 0; i < cookies.length; i++) {
    const raw = cookies[i].trim();
    if (!raw) continue;
    const eq = raw.indexOf("=");
    if (eq < 0) continue;
    const name = raw.slice(0, eq).trim();
    const value = raw.slice(eq + 1).trim();
    out += `.music.apple.com\tTRUE\t/\tFALSE\t9999999999\t${name}\t${value}\n`;
    out += `.apple.com\tTRUE\t/\tFALSE\t9999999999\t${name}\t${value}\n`;
  }
  return out;
}

export interface AppleMusicDownload {
  path: string;
  tempDir: string;
}

// Use a Set for O(1) extension lookup instead of .some() linear scan.
const AUDIO_EXTS = new Set([".m4a", ".mp3", ".flac", ".alac", ".wav", ".ogg", ".opus", ".aac"]);

export async function downloadAppleMusic(url: string): Promise<AppleMusicDownload> {
  if (!existsSync(GAMDL_BIN)) {
    throw new Error("gamdl not found at ~/.local/bin/gamdl. Install with: pipx install gamdl");
  }
  const settings = loadSettings();
  const cookies = settings.appleCookies;
  if (!cookies) {
    throw new Error("No Apple Music cookies set. Use /auth <cookies> first.");
  }
  const tempDir = join(tmpdir(), `catunes-apple-${Date.now()}`);
  mkdirSync(tempDir, { recursive: true });

  const cookiesPath = join(tempDir, "cookies.txt");
  if (cookies) {
    writeFileSync(cookiesPath, cookiesToNetscape(cookies));
  }

  return new Promise((resolve, reject) => {
    const args = [
      url,
      "-o", tempDir,
      "--temp-path", tempDir,
      "-n",
    ];
    if (cookies) {
      args.push("-c", cookiesPath);
    }

    const proc = spawn(GAMDL_BIN, args, { stdio: ["ignore", "pipe", "pipe"] });

    let stdout = "";
    let stderr = "";
    proc.stdout?.on("data", (d: Buffer) => { stdout += d.toString(); });
    proc.stderr?.on("data", (d: Buffer) => { stderr += d.toString(); });

    proc.on("close", (code) => {
      const tail = (stderr + stdout).slice(-500);
      if (code !== 0) {
        cleanupTempDir(tempDir);
        return reject(new Error(`gamdl exit ${code}:\n${tail}`));
      }
      const files = findAudioFiles(tempDir);
      if (files.length > 0 && files[0]) {
        resolve({ path: files[0], tempDir });
      } else {
        // List what gamdl actually created before cleaning up.
        const allFiles = listAllFiles(tempDir).join(", ");
        cleanupTempDir(tempDir);
        reject(new Error(
          `gamdl completed but no audio found.\n` +
          `URL: ${url}\n` +
          `Output dir: ${tempDir}\n` +
          `Files created: [${allFiles}]\n` +
          `gamdl output:\n${tail}`,
        ));
      }
    });

    proc.on("error", (err) => {
      cleanupTempDir(tempDir);
      reject(err);
    });
  });
}

/** Iterative directory walk — avoids recursive spread allocations. */
function listAllFiles(dir: string): string[] {
  const results: string[] = [];
  const stack: string[] = [dir];
  while (stack.length > 0) {
    const current = stack.pop()!;
    try {
      for (const file of readdirSync(current)) {
        const path = join(current, file);
        try {
          const st = statSync(path);
          if (st.isDirectory()) {
            stack.push(path);
          } else {
            results.push(file);
          }
        } catch {
          // skip
        }
      }
    } catch {
      // skip
    }
  }
  return results;
}

/** Iterative audio-file finder — uses Set lookup and push instead of spread. */
function findAudioFiles(dir: string): string[] {
  const results: string[] = [];
  const stack: string[] = [dir];
  while (stack.length > 0) {
    const current = stack.pop()!;
    try {
      for (const file of readdirSync(current)) {
        const path = join(current, file);
        try {
          const st = statSync(path);
          if (st.isDirectory()) {
            stack.push(path);
          } else if (AUDIO_EXTS.has(extname(file).toLowerCase())) {
            results.push(path);
          }
        } catch {
          // not accessible
        }
      }
    } catch {
      // dir not readable
    }
  }
  return results;
}

export function cleanupTempDir(tempDir: string): void {
  try {
    if (existsSync(tempDir)) rmSync(tempDir, { recursive: true, force: true });
  } catch {
    // ignore
  }
}
